service: preprocessor

plugins:
  - serverless-localstack

provider:
  name: aws
  region: eu-west-1
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  exclude:
    - ./**
  include:
    - ./dist/linux/amd64/**

custom:
  localstack:
    host: http://localhost
    endpointFile: endpoints.json
    autostart: true
    lambda:
      mountCode: True
    docker:
      sudo: False

functions:
  preprocessor:
    handler: dist/linux/amd64/preprocessor
    events:
      - http:
          path: hello
          method: get
